openapi: 3.0.3
info:
  title: Sport-Tracker-API
  version: 1.0.0
servers:
  - url: 'http://localhost:10022'
paths:
  /login:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: "Okay"
  /api/addTrack:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrackFormModel'
      responses:
        200:
          description: "Okay"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseId'
  /api/addMonthGoalDistance:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonthGoalDistanceFormModel'
      responses:
        200:
          description: "Okay"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseId'
  /api/addMonthGoalCount:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonthGoalDistanceFormModel'
      responses:
        200:
          description: "Okay"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseId'
  /api/addGpxTrack/{track_id}:
    post:
      parameters:
        - in: path
          name: track_id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                gpxTrack:
                  type: string
                  format: binary
      responses:
        200:
          description: "Okay"
  /api/tracks:
    get:
      responses:
        200:
          description: "Okay"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrackModel'
  /api/participants:
    get:
      responses:
        200:
          description: "Okay"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Participant'

components:
  schemas:
    TrackFormModel:
      type: object
      required:
        - name
        - type
        - date
        - time
        - distance
        - durationHours
        - durationMinutes
        - durationSeconds
        - customFields
      properties:
        name:
          type: string
        type:
           type: string
           example: BIKING or RUNNING
        date:
          type: string
          example: 2023-11-19
        time:
          type: string
          example: 11:23
        distance:
          type: number
          format: float
        durationHours:
          type: integer
        durationMinutes:
          type: integer
        durationSeconds:
          type: integer
        averageHeartRate:
          type: integer
        elevationSum:
          type: integer
        participants:
          type: array
          description: participant ids
          items:
            type: integer
          example: []
        customFields:
          type: object
          example: {'bike': 'Cube'}

    MonthGoalDistanceFormModel:
      type: object
      required:
        - type
        - year
        - month
        - distance_minimum
        - distance_perfect
      properties:
        type:
          type: string
          example: BIKING or RUNNING
        year:
          type: integer
          example: 2024
        month:
          type: integer
          example: 1
        distance_minimum:
          type: number
          format: float
          example: 100.0
        distance_perfect:
          type: number
          format: float
          example: 200.0

    MonthGoalCountFormModel:
      type: object
      required:
        - type
        - year
        - month
        - count_minimum
        - count_perfect
      properties:
        type:
          type: string
          example: BIKING or RUNNING
        year:
          type: integer
          example: 2024
        month:
          type: integer
          example: 1
        count_minimum:
          type: integer
          example: 3
        count_perfect:
          type: integer
          example: 5
    ResponseId:
      type: object
      properties:
        id:
          type: integer
    TrackModel:
      type: object
      required:
        - id
        - name
        - type
        - startTime
        - distance
        - duration
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
          example: BIKING or RUNNING
        startTime:
          type: string
          example: 2024-01-30 10:00:00
        distance:
          type: integer
        duration:
          type: integer
        averageHeartRate:
          type: integer
        elevationSum:
          type: integer
        participants:
          type: array
          description: participant ids
          items:
            type: integer
          example: []
        gpxFileName:
          type: string
        customFields:
          type: object
          example: { 'bike': 'Cube' }
    Participant:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
