openapi: 3.0.3
info:
  title: Sport-Tracker-API
  version: 1.0.0
servers:
  - url: 'http://localhost:10022'
paths:
  /login:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: "Okay"
  /api/addTrack:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrackFormModel'
      responses:
        200:
          description: "Okay"

components:
  schemas:
    TrackFormModel:
      type: object
      required:
        - name
        - type
        - date
        - time
        - distance
        - durationHours
        - durationMinutes
        - durationSeconds
        - customFields
      properties:
        name:
          type: string
        type:
           type: string
           example: BIKING or RUNNING
        date:
          type: string
          example: 2023-11-19
        time:
          type: string
          example: 11:23
        distance:
          type: number
          format: float
        durationHours:
          type: integer
        durationMinutes:
          type: integer
        durationSeconds:
          type: integer
        averageHeartRate:
          type: integer
        elevationSum:
          type: integer
        customFields:
          type: string
          example: {'bike': 'Cube'}