[tool.poetry]
name = "SportTracker"
version = "1.0.0"
description = "Self-hosted sport data tracking server."
authors = ["deadlocker8"]

[[tool.poetry.source]]
name = "TheCodeLabs"
url = "https://pypi.thecodelabs.de"
priority = "explicit"

[tool.poetry.dependencies]
python = "^3.11"
thecodelabs-baseutils = { version = "*", source = "TheCodeLabs" }
thecodelabs-flaskutils = { version = "*", source = "TheCodeLabs" }
flask = "3.0.0"
gevent = "23.9.1"
click = "8.1.7"
Flask-SQLAlchemy = "3.1.1"
Flask-Pydantic = "0.11.0"
Flask-Login = "0.6.3"
Flask-Bcrypt = "1.0.1"
flask-babel = "4.0.0"
python-dateutil = "2.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
