import enum


class NotificationType(enum.Enum):
    MAINTENANCE_REMINDER = 'MAINTENANCE_REMINDER'
    NEW_SHARED_PLANNED_TOUR = 'NEW_SHARED_PLANNED_TOUR'
    EDITED_SHARED_PLANNED_TOUR = 'EDITED_SHARED_PLANNED_TOUR'
    NEW_SHARED_LONG_DISTANCE_TOUR = 'NEW_SHARED_LONG_DISTANCE_TOUR'
    EDITED_SHARED_LONG_DISTANCE_TOUR = 'EDITED_SHARED_LONG_DISTANCE_TOUR'
